version: '3.3'
services:

  db:
    image: 'postgres:12'
    hostname: postgres
    container_name: postgres_container
    volumes:
      - gig_postgres_db_data:/var/lib/postgresql/data/
    env_file:
      - ./sample.env
    ports:
      - '5433:5432'
    networks:
      - gig-network


  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: gig_api_container
    command: /start_local.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./sample.env
    depends_on:
      - db
    networks:
      - gig-network


volumes:
  gig_postgres_db_data:

networks:
  gig-network: